import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";
import axios, { extractCookie } from "lib/axios";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href="https://localhost:5002/login?redirectUrl=http://localhost:3000">
          Login
        </a>&nbsp;
        <button
          onClick={async () => {
            try {
              let { data } = await axios.get(
                `http://localhost:3000/api/hello`,
                {
                  withCredentials: true,
                }
              );

              console.log(data);
            } catch (error) {
              window.location.href = "https://localhost:5002/login?redirectUrl=http://localhost:3000";
            }
          }}
        >
          Hello
        </button>
      </main>
    </div>
  );
};

export default Home;
