import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "lib/axios";

const remoteBffUrl = process.env.NEXT_PUBLIC_BACKEND_URL;
const url = process.env.NEXT_PUBLIC_URL;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href={`${remoteBffUrl}/login?redirectUrl=${url}`}>Login</a>
        <button
          onClick={async () => {
            try {
              let { data } = await axios.get(`${url}/api/hello`, {
                withCredentials: true,
              });

              console.log(data);
            } catch (error: any) {
              //console.log(error);
              window.location.href = `${remoteBffUrl}/login?redirectUrl=${url}`;
            }
          }}
        >
          Hello
        </button>
      </main>
    </div>
  );
};

export default Home;
